name: 'Report Build State to Space'
description: 'Reports the build state to Space as an extrenal check'
inputs:
  state:
    description:
      'The current state to report (one of: scheduled, pending, ready_to_start,
      failed_to_start, running, failing, succeeded, terminated, failed,
      hanging).'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Report state
      id: report-state
      uses: ./
      with:
        space-org: dimart
        space-token: ${{ secrets.SPACE_TOKEN }}
        space-project-key: XXX
        state: ${{ inputs.state }}

        # for this repo only since dimart.jetbrains.space is not setup to mirror this repo
        repository: fun-with-actions
        revision: a0eaad1be5fd94876f901842e0639cd9c4c9ea50